In [3]:
# !python --version\
# pip install numpy==1.23.5

Python 3.10.12


In [4]:
import numpy as np
import scipy

In [11]:
from numpy import sqrt as nsqrt
from math import sqrt as msqrt

In [13]:
a = 4
b = [4, 9, 16]
print(msqrt(a))
print(nsqrt(a))

print(nsqrt(b))

2.0
2.0
[2. 3. 4.]


In [14]:
print(msqrt(b)) #!!!

TypeError: ignored

In [17]:
a = np.array([1,2,3,4,5])

In [18]:
print(a[0])
print(a[1:])
print(a[:2])

1
[2 3 4 5]
[1 2]


In [21]:
print(a[::2])

[1 3 5]


In [22]:
print(np.zeros(5)) # нуль вектор
print(np.ones(5)) # одиничний вектор

v1 = np.array([1, 2, 3])
print(v1 * -1 ) #зворотній
print(np.linalg.norm(v1)) #норма

v2 = np.array([4,5,6])
print(f'Equal?: {np.array_equal(v1, v2)}')
print(f'Collinear?: {np.allclose(np.zeros_like(v1), np.cross(v1, v2))}')

a = np.array([7, 8, 9])
matrix = np.vstack((v1, v2, a))
det = np.linalg.det(matrix)
print(f'Complain?: {np.isclose(det, 0)}')

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[-1 -2 -3]
3.7416573867739413
Equal?: False
Collinear?: False
Complain?: True


In [24]:
np.ones(2)

array([1., 1.])

In [25]:
# Додавання/віднімання скаляра та вектора
a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a + 2)  # [3. 4. 5. 6. 7.]
print(a - 1)  # [0. 1. 2. 3. 4.]

# Множення на скаляр
b = 5*a
print(b)# [ 5. 10. 15. 20. 25.]

# Додавання та віднімання двох векторів
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # [5 7 9]
print(a - b)  # [-3 -3 -3]
# Скалярний добуток
print(np.dot(a, b))  # 32

# По елементне множення і ділення
print(a * b)  # [ 4 10 18]
print(b / a)  # [4.  2.5 2. ]

[3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4.]
[ 5. 10. 15. 20. 25.]
[5 7 9]
[-3 -3 -3]
32
[ 4 10 18]
[4.  2.5 2. ]


In [27]:
[i+2 for i in [1,2,3]]

[3, 4, 5]

In [28]:
np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a = np.array(
    [[[1,2,3],[4,5,6]],
     [[1,2,3],[4,5,6]]], dtype = float)
print(f'Array:\n {a}')
print(f'Shape: {a.shape}')
print(f'Number of dimensions: {a.ndim}') #a.ndim = len(a.shape)
print(f'Size (count of elements): {a.size}')
print(f'Data type of elements in array: {a.dtype}')
print(f'Byte size of elements: {a.itemsize}')
print(type(a))

Array:
 [[[1. 2. 3.]
  [4. 5. 6.]]

 [[1. 2. 3.]
  [4. 5. 6.]]]
Shape: (2, 2, 3)
Number of dimensions: 3
Size (count of elements): 12
Data type of elements in array: float64
Byte size of elements: 8
<class 'numpy.ndarray'>


In [30]:
np.ndarray(shape = (2,2,3),
           buffer = np.array([1,2,3,4,5,6,1,2,3,4,5,6]),
           dtype = 'int64',
           order = 'C'
           )

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [33]:
import numpy as np

a = np.array([[1, 2, 3],
              [0, 1, 2]])

b = np.array([[ 1, 2],
              [ 0, 4],
              [-1, 0]])

print(a.shape, b.shape)
# множення матриць
print('multi:\n', np.dot(a, b))
# Транспонування матриць
print('transp:\n',a.T)
# Зміна розмірності
print('reshape:\n',a.reshape((3, 2)))
# Плоска матриця
print('flatten:\n',a.flatten())
# Одинична матриця
print('eye:\n',np.eye(4, k=1, dtype=float))
#Обернена матриця
a1=np.array([[1, 2],
              [3, 4]])
print('invariant:\n',np.linalg.inv(a1))

(2, 3) (3, 2)
multi:
 [[-2 10]
 [-2  4]]
transp:
 [[1 0]
 [2 1]
 [3 2]]
reshape:
 [[1 2]
 [3 0]
 [1 2]]
flatten:
 [1 2 3 0 1 2]
eye:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
invariant:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [34]:
# Слайсування/ Індексація

a = np.array([
    [1, 2, 3],
     [4, 5, 6],
      [7, 8, 9]])
print(a[1, 1])
print(a[1:, 1])
print(a[0, :2])

5
[5 8]
[1 2]


In [37]:
# Для створення масиву, що містить послідовність чисел, існують два методи: np.arange та np.linspace
#Метод np.arange аналогічний методу Python range
import numpy as np

a = np.arange(5)
b = np.arange(1, 3, 0.5)
print(a)
print(b)

a = np.linspace(1, 5, num=2)
b = np.linspace(1, 3, num=3)
print(a)
print(b)

[0 1 2 3 4]
[1.  1.5 2.  2.5]
[1. 5.]
[1. 2. 3.]


In [38]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.prod())

1
5
15
3.0
120
