In [3]:
import numpy as np

In [4]:
# Створюємо вектор з першими 10 натуральними числами
my_arrey = np.arange(1, 11)

print(my_arrey)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
# Створюємо матрицю 3x3, заповнену нулями
my_matrix = np.zeros((3, 3))
print(my_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Створюємо матрицю 5x5 із випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(5, 5))
print(matrix)

[[ 5  3  8  3  8]
 [ 3  5 10  1  6]
 [ 3  4  1 10  2]
 [10  6  1  5  3]
 [ 6 10  3  6  3]]


In [7]:
# Створюємо матрицю 4x4 із випадковими дійсними числами від 0 до 1
my_array = np.random.rand(4, 4)
print(my_array)

[[0.5153256  0.79275487 0.4741235  0.48712921]
 [0.84110439 0.33453592 0.9172465  0.27546693]
 [0.4359025  0.91892325 0.86750727 0.99348009]
 [0.49307878 0.50857076 0.52170928 0.30800565]]


In [8]:
# Створюємо два одновимірних масиви розміром 5 із випадковими цілими числами від 1 до 10
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

# Виконуємо поелементне додавання, віднімання та множення
sum_result = array1 + array2
subtract_result = array1 - array2
multiply_result = array1 * array2

# результати операцій
print("Додавання:", sum_result)
print("Віднімання:", subtract_result)
print("Множення:", multiply_result)

Додавання: [13 19 13  7 16]
Віднімання: [-3 -1  3 -3  2]
Множення: [40 90 40 10 63]


In [9]:
# Створюємо два вектори розміром 7 із довільними числами
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)

# скалярний добуток векторів
dot_product = np.dot(vector1, vector2)

# результат скалярного добутку
print("Скалярний добуток:", dot_product)

Скалярний добуток: 1.659068322927792


In [10]:
import numpy as np
# Створюємо дві матриці розміром 2x2 та 2x3 із випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

# Перемножуємо матриці
result_matrix = np.dot(matrix1, matrix2)

# результат перемноження
print("\nРезультат перемноження:")
print(result_matrix)


Результат перемноження:
[[41 44 33]
 [60 48 36]]


In [11]:
# Створюємо матрицю 3x3 із випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 3))

# Знаходимо обернену матрицю
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nМатриця не має оберненої, оскільки вона є сингулярною (невиродженою).")


Обернена матриця:
[[-0.125    0.3      0.0125 ]
 [ 0.1875  -0.05    -0.16875]
 [ 0.      -0.2      0.2    ]]


In [12]:
# Створюємо матрицю 4x4 із випадковими дійсними числами від 0 до 1
matrix = np.random.rand(4, 4)

# Транспонуємо матрицю
transposed_matrix = matrix.T

# Виводимо значення транспонованої матриці
print("\nТранспонована матриця:")
print(transposed_matrix)


Транспонована матриця:
[[0.92546009 0.88988515 0.79978526 0.57788146]
 [0.07557772 0.08481492 0.53118905 0.34711274]
 [0.3988627  0.14958173 0.63333506 0.86563489]
 [0.07563034 0.14778483 0.66949852 0.68492431]]


In [13]:
# Створюємо матрицю 3x4 із випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 4))

# Створюємо вектор розміром 4 із випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=4)

# Перемножуємо матрицю на вектор
result_vector = np.dot(matrix, vector)

# Виводимо результат перемноження
print("\nРезультат перемноження:")
print(result_vector)


Результат перемноження:
[247 258 152]


In [14]:
# Створюємо матрицю 2x3 із випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)

# Створюємо вектор розміром 3 із випадковими дійсними числами від 0 до 1
vector = np.random.rand(3)

# Перемножуємо матрицю на вектор
result_vector = np.dot(matrix, vector)

# Виводимо результат перемноження
print("\nРезультат перемноження:")
print(result_vector)


Результат перемноження:
[1.35649596 0.4205995 ]


In [15]:
# Створюємо дві матриці розміром 2x2 із випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Виконуємо поелементне множення
elementwise_multiply_result = np.multiply(matrix1, matrix2)

# Виводимо результат поелементного множення
print("\nРезультат поелементного множення:")
print(elementwise_multiply_result)


Результат поелементного множення:
[[30 49]
 [45 20]]


In [16]:
# Створюємо дві матриці розміром 2x2 із випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Знаходимо матричний добуток
matrix_product_result = np.dot(matrix1, matrix2)

# Виводимо результат матричного добутку
print("\nРезультат матричного добутку:")
print(matrix_product_result)


Результат матричного добутку:
[[75 39]
 [39 27]]


In [17]:
# Створюємо матрицю 5x5 із випадковими цілими числами від 1 до 100
matrix = np.random.randint(1, 101, size=(5, 5))

# Знаходимо суму елементів матриці
sum_of_elements = np.sum(matrix)

# Виводимо результат суми елементів
print("\nСума елементів матриці:", sum_of_elements)


Сума елементів матриці: 1057


In [18]:
# Створюємо дві матриці розміром 4x4 із випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

# Знаходимо різницю матриць
matrix_difference = matrix1 - matrix2

# Виводимо результат різниці матриць
print("\nРізниця матриць:")
print(matrix_difference)


Різниця матриць:
[[-2  4 -6  0]
 [-1  1  3 -1]
 [-2  1  0  1]
 [ 5  0 -5 -6]]


In [19]:
# Створюємо матрицю 3x3 із випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 3)

# Знаходимо вектор-стовпчик сум елементів кожного рядка
row_sum_vector = np.sum(matrix, axis=1, keepdims=True)

# Виводимо результат
print("\nВектор-стовпчик сум елементів кожного рядка:")
print(row_sum_vector)


Вектор-стовпчик сум елементів кожного рядка:
[[2.40647341]
 [2.13434545]
 [0.86573207]]


In [20]:
# Створюємо матрицю 3x4 з довільними цілими числами
original_matrix = np.random.randint(1, 11, size=(3, 4))

# Створюємо матрицю, в якій кожен елемент - це квадрат відповідного елемента початкової матриці
squared_matrix = np.square(original_matrix)

# Виводимо значення матриці з квадратами
print("\nМатриця з квадратами:")
print(squared_matrix)


Матриця з квадратами:
[[ 16  16   9  16]
 [  4  36  64   4]
 [ 81   1 100   1]]


In [21]:
# Створюємо вектор розміром 4 з випадковими цілими числами від 1 до 50
original_vector = np.random.randint(1, 51, size=4)

# Створюємо вектор з квадратними коренями
sqrt_vector = np.sqrt(original_vector)

# Виводимо значення вектора з квадратними коренями
print("\nВектор з квадратними коренями:")
print(sqrt_vector)


Вектор з квадратними коренями:
[6.32455532 3.60555128 6.8556546  5.09901951]
