In [1]:
import numpy as np

In [3]:
# Створюємо вектор з першими 10 натуральними числами
my_arrey = np.arange(1, 11)

print(my_arrey)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
# Створюємо матрицю 3x3, заповнену нулями
my_matrix = np.zeros((3, 3))
print(my_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Створюємо матрицю 5x5 із випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(5, 5))
print(matrix)

[[ 6 10  2  5  5]
 [ 3  4  4  7  9]
 [ 8  8  1  4  1]
 [ 2  4  4  2  4]
 [ 5  9  8 10  2]]


In [10]:
# Створюємо матрицю 4x4 із випадковими дійсними числами від 0 до 1
my_array = np.random.rand(4, 4)
print(my_array)

[[0.74710152 0.57059829 0.55866637 0.00725857]
 [0.08199956 0.20504366 0.29064921 0.11161289]
 [0.92539252 0.99301535 0.97909862 0.84401606]
 [0.87727769 0.97982732 0.73276703 0.997406  ]]


In [11]:
# Створюємо два одновимірних масиви розміром 5 із випадковими цілими числами від 1 до 10
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

# Виводимо значення створених масивів
print("Масив 1:", array1)
print("Масив 2:", array2)

# Виконуємо поелементне додавання, віднімання та множення
sum_result = array1 + array2
subtract_result = array1 - array2
multiply_result = array1 * array2

# Виводимо результати операцій
print("Додавання:", sum_result)
print("Віднімання:", subtract_result)
print("Множення:", multiply_result)

Масив 1: [ 4  4  9  2 10]
Масив 2: [4 9 7 5 3]
Додавання: [ 8 13 16  7 13]
Віднімання: [ 0 -5  2 -3  7]
Множення: [16 36 63 10 30]


In [12]:
# Створюємо два вектори розміром 7 із довільними числами
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)

# Виводимо значення створених векторів
print("Вектор 1:", vector1)
print("Вектор 2:", vector2)

# Знаходимо скалярний добуток векторів
dot_product = np.dot(vector1, vector2)

# Виводимо результат скалярного добутку
print("Скалярний добуток:", dot_product)

Вектор 1: [0.90699905 0.6665322  0.00929822 0.34339236 0.97544327 0.84261377
 0.82456321]
Вектор 2: [0.74605332 0.19947175 0.37380647 0.0610607  0.61978542 0.22491371
 0.12889437]
Скалярний добуток: 1.7344299710034026


In [13]:
# Створюємо дві матриці розміром 2x2 та 2x3 із випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

# Виводимо значення створених матриць
print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

# Перемножуємо матриці
result_matrix = np.dot(matrix1, matrix2)

# Виводимо результат перемноження
print("\nРезультат перемноження:")
print(result_matrix)

Матриця 1:
[[10  1]
 [ 3 10]]

Матриця 2:
[[ 9  1  4]
 [ 6 10  9]]

Результат перемноження:
[[ 96  20  49]
 [ 87 103 102]]


In [14]:
# Створюємо матрицю 3x3 із випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 3))

# Виводимо значення створеної матриці
print("Матриця:")
print(matrix)

# Знаходимо обернену матрицю
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nМатриця не має оберненої, оскільки вона є сингулярною (невиродженою).")

Матриця:
[[5 9 8]
 [6 3 2]
 [8 9 4]]

Обернена матриця:
[[-0.04347826  0.26086957 -0.04347826]
 [-0.05797101 -0.31884058  0.27536232]
 [ 0.2173913   0.19565217 -0.2826087 ]]


In [15]:
# Створюємо матрицю 4x4 із випадковими дійсними числами від 0 до 1
matrix = np.random.rand(4, 4)

# Виводимо значення створеної матриці
print("Матриця:")
print(matrix)

# Транспонуємо матрицю
transposed_matrix = matrix.T

# Виводимо значення транспонованої матриці
print("\nТранспонована матриця:")
print(transposed_matrix)

Матриця:
[[0.79788336 0.9500205  0.11953423 0.71341285]
 [0.17856552 0.20774216 0.05873956 0.88070292]
 [0.18892022 0.42368709 0.86126669 0.04416582]
 [0.33986572 0.66410781 0.206434   0.3645149 ]]

Транспонована матриця:
[[0.79788336 0.17856552 0.18892022 0.33986572]
 [0.9500205  0.20774216 0.42368709 0.66410781]
 [0.11953423 0.05873956 0.86126669 0.206434  ]
 [0.71341285 0.88070292 0.04416582 0.3645149 ]]


In [16]:
# Створюємо матрицю 3x4 із випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 4))

# Створюємо вектор розміром 4 із випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=4)

# Виводимо значення створеної матриці та вектора
print("Матриця:")
print(matrix)

print("\nВектор:")
print(vector)

# Перемножуємо матрицю на вектор
result_vector = np.dot(matrix, vector)

# Виводимо результат перемноження
print("\nРезультат перемноження:")
print(result_vector)

Матриця:
[[10  8  7  3]
 [ 9  4  2  5]
 [10  9  6  1]]

Вектор:
[9 6 1 7]

Результат перемноження:
[166 142 157]


In [17]:
# Створюємо матрицю 2x3 із випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)

# Створюємо вектор розміром 3 із випадковими дійсними числами від 0 до 1
vector = np.random.rand(3)

# Виводимо значення створеної матриці та вектора
print("Матриця:")
print(matrix)

print("\nВектор:")
print(vector)

# Перемножуємо матрицю на вектор
result_vector = np.dot(matrix, vector)

# Виводимо результат перемноження
print("\nРезультат перемноження:")
print(result_vector)

Матриця:
[[0.91764491 0.1079177  0.80600655]
 [0.2095059  0.51792739 0.33749463]]

Вектор:
[0.68304282 0.6097246  0.57455332]

Результат перемноження:
[1.15568458 0.65280323]


In [18]:
# Створюємо дві матриці розміром 2x2 із випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Виводимо значення створених матриць
print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

# Виконуємо поелементне множення
elementwise_multiply_result = np.multiply(matrix1, matrix2)

# Виводимо результат поелементного множення
print("\nРезультат поелементного множення:")
print(elementwise_multiply_result)

Матриця 1:
[[1 6]
 [4 1]]

Матриця 2:
[[ 6  9]
 [ 6 10]]

Результат поелементного множення:
[[ 6 54]
 [24 10]]


In [19]:
# Створюємо дві матриці розміром 2x2 із випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Виводимо значення створених матриць
print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

# Знаходимо матричний добуток
matrix_product_result = np.dot(matrix1, matrix2)

# Виводимо результат матричного добутку
print("\nРезультат матричного добутку:")
print(matrix_product_result)

Матриця 1:
[[ 7  9]
 [10  5]]

Матриця 2:
[[ 7 10]
 [ 6  3]]

Результат матричного добутку:
[[103  97]
 [100 115]]


In [20]:
# Створюємо матрицю 5x5 із випадковими цілими числами від 1 до 100
matrix = np.random.randint(1, 101, size=(5, 5))

# Виводимо значення створеної матриці
print("Матриця:")
print(matrix)

# Знаходимо суму елементів матриці
sum_of_elements = np.sum(matrix)

# Виводимо результат суми елементів
print("\nСума елементів матриці:", sum_of_elements)

Матриця:
[[55 33  9 82 71]
 [21 28 16 81 97]
 [63 21 45 93  9]
 [ 2 13 63 85  4]
 [26 17 45 70 22]]

Сума елементів матриці: 1071


In [21]:
# Створюємо дві матриці розміром 4x4 із випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

# Виводимо значення створених матриць
print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

# Знаходимо різницю матриць
matrix_difference = matrix1 - matrix2

# Виводимо результат різниці матриць
print("\nРізниця матриць:")
print(matrix_difference)

Матриця 1:
[[9 6 9 3]
 [7 2 9 5]
 [9 1 1 2]
 [6 4 8 7]]

Матриця 2:
[[ 7  6  3  6]
 [ 1 10  9  7]
 [ 1  2  1  2]
 [ 3  8 10  3]]

Різниця матриць:
[[ 2  0  6 -3]
 [ 6 -8  0 -2]
 [ 8 -1  0  0]
 [ 3 -4 -2  4]]


In [22]:
# Створюємо матрицю 3x3 із випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 3)

# Виводимо значення створеної матриці
print("Матриця:")
print(matrix)

# Знаходимо вектор-стовпчик сум елементів кожного рядка
row_sum_vector = np.sum(matrix, axis=1, keepdims=True)

# Виводимо результат
print("\nВектор-стовпчик сум елементів кожного рядка:")
print(row_sum_vector)

Матриця:
[[0.19244451 0.77829075 0.81083962]
 [0.5238899  0.48330863 0.56784928]
 [0.39615636 0.97558186 0.35675213]]

Вектор-стовпчик сум елементів кожного рядка:
[[1.78157488]
 [1.57504781]
 [1.72849035]]


In [23]:
# Створюємо матрицю 3x4 з довільними цілими числами
original_matrix = np.random.randint(1, 11, size=(3, 4))

# Виводимо значення початкової матриці
print("Початкова матриця:")
print(original_matrix)

# Створюємо матрицю, в якій кожен елемент - це квадрат відповідного елемента початкової матриці
squared_matrix = np.square(original_matrix)

# Виводимо значення матриці з квадратами
print("\nМатриця з квадратами:")
print(squared_matrix)

Початкова матриця:
[[7 5 3 3]
 [9 9 5 8]
 [1 2 9 8]]

Матриця з квадратами:
[[49 25  9  9]
 [81 81 25 64]
 [ 1  4 81 64]]


In [24]:
# Створюємо вектор розміром 4 з випадковими цілими числами від 1 до 50
original_vector = np.random.randint(1, 51, size=4)

# Виводимо значення початкового вектора
print("Початковий вектор:")
print(original_vector)

# Створюємо вектор з квадратними коренями
sqrt_vector = np.sqrt(original_vector)

# Виводимо значення вектора з квадратними коренями
print("\nВектор з квадратними коренями:")
print(sqrt_vector)

Початковий вектор:
[ 8 30 50 32]

Вектор з квадратними коренями:
[2.82842712 5.47722558 7.07106781 5.65685425]
